#! /usr/bin/env bash

export __HD5WEB_VERSION__=0.01

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"
lib_path="${local_path}/hd5web-${__HD5WEB_VERSION__}"

. "${lib_path}/logging"
. "${lib_path}/hdf5"
