#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"

hdf5::files() {
    echo "${HD5WEB_FILES}" | sed -e 's/^[\s]*//g' -e 's/[\r]*$//g' -e '/^[\r]*$/d'
}

hdf5::dir() {
    local _filename="${1:?Need filename}"

    h5dump -n "${_filename}" | awk '/^FILE_CONTENTS[ ]/{on=1;} /^[ ][\}]/{on=0;} {if (on) {printf("%s %s\n", $1, $2);}}' on=0
}