#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"

. "${local_path}/logging"

hdf5::version() {
    echo "${__HD5WEB_VERSION__}"
}

hdf5::map() {
    local _function="${1:?Must supply a function name}"
    local _row

    while read _row
    do
        "${_function}" "${_row}"
    done
}

hdf5::add_files() {
    __HD5WEB_FILES__="$((echo "${__HD5WEB_FILES__}"; echo "${1}") | sed -e 's/^[\s]*//g' -e 's/[\s]*$//g' -e '/^[\s]*$/d')"
}

hdf5::files() {
    echo "${__HD5WEB_FILES__}" | sed -e 's/^[\s]*//g' -e 's/[\s]*$//g' -e '/^[\s]*$/d'
}

hdf5::dir() {
    local _filename="${1:?Need filename}"

    h5dump -n "${_filename}" | awk '
        /^[ ]*FILE_CONTENTS[ ][ ]*/ {
            on=1;
        }

        /^[ ][}]/ {
            on=0;
        }

        {
            if (on == 1) {
                on = 2;
            }
            else if (on) {
                printf("filename=\"%s\" type=\"%s\" path=\"%s\"\n", filename, $1, $2);
            }
        }' on=0 filename="${_filename}"
}