#! /usr/bin/env bash

http::hdf5::url_mappings() {
    url::add_handler '^\/$' GET http::hdf5::response_index
    url::add_handler '^\/index.html$' GET http::hdf5::response_index
    url::add_handler '^\/api\/files[\/]*$' GET http::hdf5::get_filelist
    url::add_handler '^\/api\/tree[\/]*$' GET http::hdf5::get_tree
    url::add_handler '^\/static\/.*$' GET http::response_file
}

http::hdf5::response_index() {
    http::response_file GET index.html "${3}"
}

http::hdf5::get_filelist() {
    . "$("${__HD5WEB_BINARY__}" --lib)"

    hdf5::files | {
        echo "{"
        echo "\"files\": ["
        awk '{printf("%s\"%s\"\n", sep, $0); sep=",";}'
        echo "]"
        echo "}"
    } | http::response_json
}

http::hdf5::get_tree() {
    . "$("${__HD5WEB_BINARY__}" --lib)"

    h5dump -n "${__HD5WEB_HDF5FILE__}" /tmp/demo.h5 | while read type path
    do
        :
    done
}