#! /usr/bin/env bash

first_name="${BASH_SOURCE[0]}"
actual_name="$(readlink -f "${first_name}")"
local_path="$(dirname "${actual_name}")"
library_import_file="$(readlink -f "${local_path}/../lib/hd5web")"
share_folder="$(readlink -f "${local_path}/../share/hd5web")"

#===================================================================================
#                              Set defaults
#===================================================================================
export __HD5WEB_BINARY__="${actual_name}"
export __HD5WEB_FILES__=
listener_port=7272

#===================================================================================
#                          Import hd5web library
#===================================================================================
. "${library_import_file}"

#===================================================================================
#                              Help Message
#===================================================================================
showhelp()
{
    contents=$(
        echo "${*}" |
        awk -F, '{for (i=1; i <= NF; ++i) {print $i;}}' |
        awk -F: '{printf("%s[--%s%s]", sep, $1, (NF == 2 ? sprintf("=<%s>", $1) : "")); sep=" "}'
    )

    echo "Usage: $0 ${contents}" >&2
}

#===================================================================================
# NOTE: There is a bug in getopts where not specifying at least one short option
#       will cause the first non option parameter to be discarded. Here, we just
#       use -h (help)
#===================================================================================
long_options="help,version,debug,info,warning,fatal,hdf5:,port:,share,lib"

OPTION_TEMP=$(getopt -a -o hv --long ${long_options} -- "$@")

if [ $? != 0 ]
then
    logging::fatal "Invalid command line options ${OPTION_TEMP}"
fi

eval set -- "$OPTION_TEMP"

#===================================================================================
#                       Process command line parameters
#
# NOTE: The command line parameters are available for scripts which
#       source this file.
#===================================================================================
while true
do
    case "$1" in
        --debug|--info|--warning|--fatal)
            logging::set_severity "$(echo "${1}" | sed -e 's/^[\-]*//g')"
            shift
            ;;

        --lib)
            echo "${library_import_file}"
            shift
            exit 0
            ;;

        --share)
            echo "${share_folder}"
            shift
            exit 0
            ;;

        --hdf5)
            hdf5::add_files "${2}"
            shift 2
            ;;

        --port)
            listener_port="${2}"
            shift 2
            ;;

        --version|-v)
            hdf5::version
            exit 0
            ;;

        --)
            shift
            break
            ;;

        *)
            showhelp "${long_options}" >&2
            exit 0
            ;;
    esac
done

exec "${share_folder}/tools/webserve" \
    --static="${share_folder}/static" \
    --module="${share_folder}/plugins/hdf5_plugin" \
    --port="${listener_port:?Need a port number}"
